version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  backend:
    build:
      context: .
      dockerfile: Fastapi_Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
